import React, { useState } from 'react';
import Head from 'next/head';
import Script from 'next/script';
import Header from '../components/base/Header';
import Login from '../components/base/Login';

const Layout = ({ children }) => {
  const [showLanguageOptions, setShowLanguageOptions] = useState(false);
  const [showLogin, setShowLogin] = useState(false);

  const outsideClick = () => {
    setShowLanguageOptions(false);
  };

  return (
    <>
      <Head>
        <title>Tower</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Script src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js" />
      <Script src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js" />

      <Header
        outsideClick={ outsideClick }
        showLanguageOptions={showLanguageOptions}
        setShowLanguageOptions={setShowLanguageOptions}
        showLogin={showLogin}
        setShowLogin={setShowLogin}
      />

      {showLogin && <Login setShowLogin={setShowLogin} />}

      <div onClick={ outsideClick }>
        {children}
      </div>
    </>
  );
};

export default Layout;
